import 'bootstrap/dist/css/bootstrap.css';
import BootstrapClient from '@/components/BootstrapClient.js';
import { Inter } from "next/font/google";
import "./globals.css";
import '../public/assets/css/plugins/animation.css'
import '../public/assets/css/plugins/feature.css'
import '../public/assets/css/plugins/magnify.min.css'
import '../public/assets/css/plugins/slick.css'
import '../public/assets/css/plugins/slick-theme.css'
import '../public/assets/css/plugins/lightbox.css'
import '../public/assets/css/plugins/bootstrap-select.min.css'
import '../public/assets/css/plugins/prism.css'
import '../public/assets/css/style.css'
import Script from 'next/script';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      
      </body>
      <Script async src="../assets/js/vendor/modernizr.min.js"></Script>
    <Script src="../assets/js/vendor/jquery.min.js"></Script>
    <Script async src="../assets/js/vendor/bootstrap.min.js"></Script>
    <Script async src="../assets/js/vendor/popper.min.js"></Script>
    <Script async src="../assets/js/vendor/waypoint.min.js"></Script>
    <Script async src="../assets/js/vendor/wow.min.js"></Script>
    <Script async src="../assets/js/vendor/counterup.min.js"></Script>
    <Script async src="../assets/js/vendor/feather.min.js"></Script>
    <Script async src="../assets/js/vendor/sal.min.js"></Script>
    <Script async src="../assets/js/vendor/backto-top.js"></Script>
    <Script async src="../assets/js/vendor/masonry.js"></Script>
    <Script async src="../assets/js/vendor/imageloaded.js"></Script>
    <Script async src="../assets/js/vendor/magnify.min.js"></Script>
    <Script async src="../assets/js/vendor/lightbox.js"></Script>
    <Script async src="../assets/js/vendor/slick.min.js"></Script>
    <Script async src="../assets/js/vendor/easypie.js"></Script>
    <Script async src="../assets/js/vendor/text-type.js"></Script>
    <Script async src="../assets/js/vendor/prism.js"></Script>
    <Script async src="../assets/js/vendor/jquery.style.swicher.js"></Script>
    <Script async src="../assets/js/vendor/bootstrap-select.min.js"></Script>

    <Script async src="../assets/js/vendor/js.cookie.js"></Script>
    <Script async src="../assets/js/vendor/jquery-one-page-nav.js"></Script>
   
    <Script async src="../assets/js/main.js"></Script>
    </html>
  );
}
